version: '3.8'
services:
  lab2-node1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lab2-node1-container
    ports:
      - "8081:8081" # Expose the internal 8080 port on 8081
      - "5001:5000" # Expose the internal 5000 port on 5001
    depends_on:
      - sql-server
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - NODE_ID=node1 # Unique identifier for this node
      - PEERS=node2:8082,node3:8083 # Other node addresses
      - NODE_PORT=8081
    networks:
      - lab2_default

  lab2-node2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lab2-node2-container
    ports:
      - "8082:8082" # Expose the internal 8080 port on 8082
      - "5002:5000" # Expose the internal 5000 port on 5002
    depends_on:
      - sql-server
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - NODE_ID=node2 # Unique identifier for this node
      - PEERS=node1:8081,node3:8083 # Other node addresses
      - NODE_PORT=8082
    networks:
      - lab2_default

  lab2-node3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lab2-node3-container
    ports:
      - "8083:8083" # Expose the internal 8080 port on 8083
      - "5003:5000" # Expose the internal 5000 port on 5003
    depends_on:
      - sql-server
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - NODE_ID=node3 # Unique identifier for this node
      - PEERS=node1:8081,node2:8082 # Other node addresses
      - NODE_PORT=8083
    networks:
      - lab2_default

  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2019-CU17-ubuntu-20.04
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "#1324aAa1324"
    ports:
      - "1433:1433"
    volumes:
      - my-volume:/var/opt/mssql/data
    user: root
    networks:
      - lab2_default

volumes:
  my-volume:

networks:
  lab2_default:
