services:
  lab2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lab2-cotainer
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - sql-server
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "#1324aAa1324"
    ports:
      - "1433:1433"
    volumes:
      - my-volume:/var/opt/mssql/data
    user:
      root

volumes:
  my-volume: