services:
  mssql:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "#1324aAa1324"
    ports:
      - "1433:1433"
    volumes:
      - my-volume:/var/opt/mssql/data
    user:
      root

volumes:
  my-volume: