version: '3.8'
services:
  lab2-node1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lab2-node1-container
    ports:
      - "8081:8080/udp"
      - "5001:5000/tcp" # HTTP-based port
    depends_on:
      - sql-server
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - NODE_ID=node1
      - PEERS=lab2-node2:8082,lab2-node3:8083,lab2-node4:8084
      - NODE_PORT=8081
    networks:
      - lab2_default

  lab2-node2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lab2-node2-container
    ports:
      - "8082:8080/udp"
      - "5002:5000/tcp" # HTTP-based port
    depends_on:
      - sql-server
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - NODE_ID=node2
      - PEERS=lab2-node1:8081,lab2-node3:8083,lab2-node4:8084
      - NODE_PORT=8082
    networks:
      - lab2_default

  lab2-node3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lab2-node3-container
    ports:
      - "8083:8080/udp"
      - "5003:5000/tcp" # HTTP-based port
    depends_on:
      - sql-server
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - NODE_ID=node3
      - PEERS=lab2-node1:8081,lab2-node2:8082,lab2-node4:8084
      - NODE_PORT=8083
    networks:
      - lab2_default
  lab2-node4:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lab2-node4-container
    ports:
      - "8084:8080/udp"
      - "5004:5000/tcp" # HTTP-based port
    depends_on:
      - sql-server
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - NODE_ID=node4
      - PEERS=lab2-node1:8081,lab2-node2:8082,lab2-node3:8083
      - NODE_PORT=8084
    networks:
      - lab2_default
  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2019-CU17-ubuntu-20.04
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "#1324aAa1324"
    ports:
      - "1433:1433"
    volumes:
      - my-volume:/var/opt/mssql/data
    user: root
    networks:
      - lab2_default

volumes:
  my-volume:

networks:
  lab2_default:
    driver: bridge